### PR TITLE
Release command should reject binaries

### LINKED ISSUE #102: Release command should reject binary files
Currently, the release command will detect if a zip file is specified as the packager parameter and reject it. In order to reduce potential errors, we should also reject APK and ipa files (which are also zips), so that devs can't accidentally release binaries and get confused with why their app fails when trying to update.

### PR DESCRIPTION
**Pull request by shishirx34**
This fixes #102 - Release command should reject binaries.

Also added tests for release command in CLI.

### CODE REVIEW

File: cli/script/command-executor.ts [hunk 1]
```diff
@@ -742,8 +742,8 @@ function promote(command: cli.IPromoteCommand): Promise<void> {
 }
 
 function release(command: cli.IReleaseCommand): Promise<void> {
-    if (command.package.search(/\.zip$/i) !== -1) {
-        throw new Error("It is unnecessary to package releases in a .zip file. Please specify the path of the desired directory or file directly.");
+    if (isBinaryOrZip(command.package)) {
+        throw new Error("It is unnecessary to package releases in a .zip or binary file. Please specify the path of the desired directory or file directly.");
```
Comment (lostintangent) [inline cli/script/command-executor.ts]: What about changing the second sentence to something like this?: "Please specify the direct path to the update content's directory (e.g. /platforms/ios/www) or file (e.g. main.jsbundle)."

That way, in addition to rejecting the binaries, we also provide an example of what the parameter expects.

**Comment by lostintangent** [comment]
LGTM! Thanks for taking care of this!

File: cli/script/command-executor.ts [hunk 2]
```diff
@@ -908,6 +908,12 @@ function tryBase64Decode(encoded: string): string {
     }
 }
 
+function isBinaryOrZip(path: string): boolean {
+    return path.search(/\.zip$/i) !== -1
+            || path.search(/\.apk$/i) !== -1
+            || path.search(/\.ipa$/i) !== -1;
+}
```
Comment (dtivel) [inline cli/script/command-executor.ts]: Format document.  (8 spaces before ||.)

File: cli/script/command-executor.ts (hunk 1 above)
Comment (shishirx34) [inline cli/script/command-executor.ts]: sounds good to me.

File: cli/test/cli.ts [hunk 3]
```diff
@@ -497,4 +501,73 @@ describe("CLI", () => {
...
+                }
+            });
+    });
+
+    it("release doesn't allow releasing .ipa file", (done: MochaDone): void => {
+        var command: cli.IReleaseCommand = {
+            type: cli.CommandType.release,
+            appName: "a",
+            deploymentName: "Staging",
+            description: "test releasing zip file",
```
Comment (dtivel) [inline cli/test/cli.ts]: ipa

File: cli/test/cli.ts [hunk 4]
```diff
@@ -497,4 +501,73 @@ describe("CLI", () => {
...
+                }
+            });
+    });
+
+    it("release doesn't allow releasing .apk file", (done: MochaDone): void => {
+        var command: cli.IReleaseCommand = {
+            type: cli.CommandType.release,
+            appName: "a",
+            deploymentName: "Staging",
+            description: "test releasing zip file",
```
Comment (dtivel) [inline cli/test/cli.ts]: apk

File: cli/script/command-executor.ts [hunk 5]
```diff
@@ -742,8 +742,8 @@ function promote(command: cli.IPromoteCommand): Promise<void> {
 }
 
 function release(command: cli.IReleaseCommand): Promise<void> {
-    if (command.package.search(/\.zip$/i) !== -1) {
-        throw new Error("It is unnecessary to package releases in a .zip file. Please specify the path of the desired directory or file directly.");
+    if (isBinaryOrZip(command.package)) {
+        throw new Error("It is unnecessary to package releases in a .zip or binary file. Please specify the direct path to the update content's directory (e.g. /platoforms/ios/www) or file (e.g. main.jsbundle).");
```
Comment (lostintangent) [inline cli/script/command-executor.ts]: Sorry, I had a typo in my string suggestion :) It should be `/platforms/ios/www'.

Comment (shishirx34) [inline cli/script/command-executor.ts]: Oh you didn't that was my typo :(

File: cli/test/cli.ts [hunk 6]
```diff
@@ -497,4 +501,73 @@ describe("CLI", () => {
...
+        var release: Sinon.SinonSpy = sandbox.spy(cmdexec.sdk, "release");
+
+        cmdexec.execute(command)
+            .done((): void => {
+            }, (error: any): void => {
+                if (error) {
+                    assert.equal(error.message, "It is unnecessary to package releases in a .zip or binary file. Please specify the path of the desired directory or file directly.");
+                    done();
+                }
+            });
```
Comment (dtivel) [inline cli/test/cli.ts]: const RELEASE_FAILED_ERROR_MESSAGE = "...";
    
    ...
    
    cmdexec.execute(command)
        .done((): void => throw Error("Error expected"), (error: any): void => {
            assert(!!error);
            assert.equal(error.message, RELEASE_FAILED_ERROR_MESSAGE);
            done();
        });

This way the error message is deduplicated, the done() resolved and rejected-with-no-error code paths throw a clear error (instead of timing out).  You could also deduplicate the `command` initialization with a helper function.

File: cli/script/command-executor.ts [hunk 7]
```diff
@@ -908,6 +908,12 @@ function tryBase64Decode(encoded: string): string {
     }
 }
 
+function isBinaryOrZip(path: string): boolean {
+    return path.search(/\.zip$/i) !== -1
+    || path.search(/\.apk$/i) !== -1
+    || path.search(/\.ipa$/i) !== -1;
```
Comment (dtivel) [inline cli/script/command-executor.ts]: (8 spaces)||

1 level of indentation is 4 spaces.

File: cli/test/cli.ts [hunk 8]
```diff
@@ -497,4 +502,63 @@ describe("CLI", () => {
...
+            type: cli.CommandType.release,
+            appName: "a",
+            deploymentName: "Staging",
+            description: "test releasing zip file",
+            mandatory: false,
+            appStoreVersion: "1.0.0",
+            package: "/fake/path/test/file.zip"
+        };
+
+        var release: Sinon.SinonSpy = sandbox.spy(cmdexec.sdk, "release");
```
Comment (dtivel) [inline cli/test/cli.ts]: You can move this inside releaseHelperFunction(...).

Same for subsequent tests.

**Comment by dtivel** [comment]
Looks good.

File: cli/script/command-executor.ts (hunk 7 above)
Comment (shishirx34) [inline cli/script/command-executor.ts]: I see.. I thought you meant remove 8 spaces of indentation that I had previous to this change.
